### ISSUE TITLE
Issues when setting up node IP addresses

### ISSUE THREAD

**Issue by weiliangz** [AURIN/comp90024#1]
I tried to setup the couchDB cluster following the instructions here, and got some questions.

When using `export declare -a nodes=()` to set node IP addresses, I received a message:
`-bash: export: '-a': not a valid identifier`, and I'm wondering what does this `-a` do exactly. 

Thanks!

**Comment by lmoran** [comment]
`declare -a` sets a variable an [array](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_02.html). 
that message seems to be just a warning.
To try out how array variables work:
```
export declare -a nodes=(1,2,3,4)
echo ${nodes[@]}
```
